### ISSUE TITLE
Image not correct orientated 

### ISSUE THREAD

**Issue by Jakkajakka** [ToastHawaii/public-bookcase-map#1]
Images from https://commons.wikimedia.org/wiki/File:Bookcase_-_Le_Chaperon_Rouge.jpg is not detected that it is taken in portraits orientation.
https://public-bookcase.github.io/map.html#50.8475015,4.3952595

**Comment by Binnette** [comment]
Hi @Jakkajakka, i fixed the issue. Feel free to test it on several image, then close this bug if your tests are OK.

**Comment by Jakkajakka** [comment]
Search for some image  and it look good thx
