### ISSUE TITLE
Message "No locations found" can be more explicit

### ISSUE THREAD

**Issue by Binnette** [ToastHawaii/public-bookcase-map#12]
Hi @ToastHawaii, hope you're doing great.

On the map when no bookcase is found, the message "No locations found" is displayed.

I was wondering if you can change it to "No bookcase found in this area". Because with the current message I was thinking the app could not find my "location".

Have a nice day.

**Comment by ToastHawaii** [comment]
Changed with https://github.com/ToastHawaii/public-bookcase-map/commit/68bdbb0cdae2e277dd0c094c06a046134b6c6f21
