### ISSUE TITLE
Image not working when using commons category

### ISSUE THREAD

**Issue by Binnette** [ToastHawaii/public-bookcase-map#6]
Hi @ToastHawaii,

I am testing unbezahlbar and i found a bug 😉

![image](https://user-images.githubusercontent.com/6597721/65453343-4c8d1400-de43-11e9-9731-afd99a6be339.png)

You can reproduce the bug by heading to this way:
https://www.openstreetmap.org/way/404461024

Given the article [Key:wikimedia_commons](https://wiki.openstreetmap.org/wiki/Key:wikimedia_commons), you can set wikimedia_commons to a "File" or a "Category". So I tried to link to a "Category". Unfortunately "unbezahlbar" can not managed "Category". We should consider changing function "toWikimediaCommensUrl" to handle this case.

💡 BTW function "toWikimediaCommensUrl" is incorrectly named. Correct name should be "toWikimediaCommonsUrl" with 2 "o" on "commons" instead of "commens".

**Comment by ToastHawaii** [comment]
Hello @Binnette
Thanks for the hint. I have added a handling for categories in both projects. They will be converted into a link.
https://unbezahlbar.github.io/map.html#45.1657418,5.7842967
Best regards :)

**Comment by Binnette** [comment]
Hi @ToastHawaii ,

1. I clicked on your link
1. I tested your solution
1. I loved it 👍 

Thanks a lot for your fix 😉
